-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CASTING_CLOSED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BRAND_PROFILE_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BRAND_PROFILE_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROFILE_SUSPENDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PREMIUM_EXPIRING';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PREMIUM_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'WELCOME';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LOGIN_SUCCESSFUL';
