import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
const baseUrl = "https://delhicastingagency.com";

  const routes = [
    "/",
    "/about-us/",
    "/actors/",
    "/actors/experienced-actors/",
    "/actors/female-actors/",
    "/actors/fresh-faces/",
    "/actors/male-actors/",
    "/blog/",
    "/blog/acting-audition-tips/",
    "/blog/category/actors/",
    "/blog/category/industry-news/",
    "/blog/category/models/",
    "/blog/how-to-avoid-casting-scams/",
    "/blog/how-to-become-an-actor-in-bollywood/",
    "/blog/how-to-build-a-modeling-portfolio/",
    "/casting-calls/",
    "/casting-calls/actors/",
    "/casting-calls/bollywood-films/",
    "/casting-calls/dancers/",
    "/casting-calls/fashion-shows/",
    "/casting-calls/influencers/",
    "/casting-calls/models/",
    "/casting-calls/music-videos/",
    "/casting-calls/ott-web-series/",
    "/casting-calls/print-ads/",
    "/casting-calls/tv-commercials/",
    "/casting-calls/tv-serials/",
    "/casting-calls/voice-artists/",
    "/child-artists/",
    "/community-access/",
    "/contact-us/",
    "/dancers/",
    "/dancers/background-dancers/",
    "/dancers/lead-dancers/",
    "/disclaimer/",
    "/faq/",
    "/how-it-works/",
    "/influencers/",
    "/influencers/instagram-influencers/",
    "/influencers/youtube-influencers/",
    "/membership/",
    "/models/",
    "/models/commercial-model/",
    "/models/commercial-models/",
    "/models/fashion-models/",
    "/models/female-models/",
    "/models/fitness-models/",
    "/models/male-models/",
    "/models/plus-size-models/",
    "/payment/",
    "/privacy-policy/",
    "/refund-and-cancellation-policy/",
    "/profile/setup/",
    "/register/brand/",
    "/success-stories/",
    "/talents/",
    "/terms-and-conditions/",
    "/voice-artists/",
    "/voice-artists/dubbing-artists/",
    "/voice-artists/radio-voice-artists/",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
  }));
}
